"""test if db is working

Revision ID: ce685c028fac
Revises: 2fa57594b6d5
Create Date: 2020-07-25 09:47:33.495636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce685c028fac'
down_revision = '2fa57594b6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_post_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_fkey', 'comment', 'post', ['post'], ['id'])
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
