""" second commit

Revision ID: e35824c10b5c
Revises: dfa7348c6856
Create Date: 2020-07-24 18:19:53.296290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35824c10b5c'
down_revision = 'dfa7348c6856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('user', 'pass_secure')
    # ### end Alembic commands ###
